name: Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout Unbound
        uses: actions/checkout@v2
        with:
          repository: nlnetlabs/unbound
          path: ub

      - name: Install Unbound
        working-directory: ub
        run: ./configure &&
             make &&
             sudo make install &&
             sudo ldconfig

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1

      - name: Install
        run: npm install

      - name: Test
        run: npm run test

      - name: Browser Test
        run: npm install browserify && npm run test-browser
